- spec/peg_zone_spec.md
Added some documentation of the design we decided against.
> Discussion of the rejected design B

- witness/Cargo.lock
- witness/Cargo.toml
- witness/Peggy.abi
- witness/SolidityToy.abi
- witness/rustfmt.toml
- witness/src/errors.rs
- witness/src/main.rs
- witness/src/tx.rs
> Revert "Revert "Baseline ETH tailing rust code""

- CHANGELOG.md
- README.md
Feel free to add new tags to the changelog
> add changelog and update README

- CHANGELOG.md
- x/ethbridge/handler.go
- x/ethbridge/handler_test.go
- x/ethbridge/types/events.go
Note: This PR is pointing to  cosmos:musnit/update_new_sdk and ideally that branch should be reviewed and merged first
> Add cosmos events to handler

- testnet-contracts/.env.example
- testnet-contracts/scripts/getBridgeContractAddress.js
- testnet-contracts/scripts/getTokenContractAddress.js
- testnet-contracts/scripts/sendApproveTx.js
- testnet-contracts/scripts/sendLockTx.js
- testnet-contracts/truffle-config.js
Hotfix which updates the Ethereum relayer scripts to be compatible with Infura's v3 endpoints and resolves https://github.com/cosmos/peggy/issues/84. These fixes have been implemented in pending PRs https://github.com/cosmos/peggy/pull/71 and https://github.com/cosmos/peggy/pull/77, but as those are still undergoing review this PR should be merged into master immediately.
> Updated user scripts and infura endpoint

- CHANGELOG.md
- app/app.go
- x/ethbridge/alias.go
- x/ethbridge/handler.go
- x/ethbridge/handler_test.go
- x/ethbridge/module.go
- x/ethbridge/querier/querier_test.go
- x/ethbridge/test_common.go
- x/oracle/alias.go
- x/oracle/keeper/keeper_test.go
- x/oracle/keeper/test_common.go
As part of the task to add burning to burn cEth to be sent back to ether, I've updated to use the supply module.
I'm not 100% sure it was integrated properly, as the docs on it are still limited but I think it's good and it all works well. Let me know if any issues, thanks!
> Update to use new supply module

- x/ethbridge/handler.go
- x/ethbridge/handler_test.go
______
For Admin Use:
- Added appropriate labels to PR (eg. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))
> remove duplicate code and broken test introduced in merge conflict resolution

- README.md
- x/ethbridge/client/cli/tx.go
______
For Admin Use:
- Added appropriate labels to PR (eg. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))
> ebcli claim-type hotfix

- README.md
PR https://github.com/cosmos/peggy/pull/98 included the removal of a step from the README, but this change was incorrect. This PR reintroduces the original step and updates it to resolve the original error.
Original step:
```
ebcli tx ethbridge create-claim 1 0x7B95B6EC7EbD73572298cEf32Bb54FA408207359 $(ebcli keys show testuser -a) $(ebcli keys show validator -a --bech val) 1stake burn --from=validator --chain-id=peggy --yes
```
Original error:
`ERROR: accepts 10 arg(s), received 6`
Updated step:
```
ebcli tx ethbridge create-claim 1 0xC4cE93a5699c68241fc2fB503Fb0f21724A624BB 0 stake 0x3f5dab653144958ff6d309647baf1abde8da204d 0x7B95B6EC7EbD73572298cEf32Bb54FA408207359 $(ebcli keys show testuser -a) $(ebcli keys show validator -a --bech val) 1stake burn --from=validator --chain-id=peggy …
```
> Readme step reintroduced and updated

- cmd/ebrelayer/events/ethereumEvent.go
This PR fixes an issue with logging Ethereum events.
______
For contributor use:
______
For admin use:
> Fix relayer log formatting of ethereum events

- testnet-contracts/truffle-config.js
Closes: #159 
______
For contributor use:
______
For admin use:
> remove flat config line

- docs/setup-bridge-chain.md
> Fix missing chain-id in docs

- .circleci/config.yml
- .github/workflows/linter.yml
- .github/workflows/tests.yml
- README.md
migrate somethings to github actions
> migrate codecov to github actions

- solidity/contracts/Peggy.sol
computes the total fee to pay to the submitBatch caller and transfers the total ERC-20 amount in one call
> token transfer optimization

- notes.md
- solidity/contracts/Peggy.sol
- solidity/test-utils/index.ts
- solidity/test/constructor.ts
This adds full failure tests for the Peggy contract constructor, and fixes a subtle bug found while writing the tests
> Constructor tests

- .github/workflows/CODEOWNERS
Setup codeowners for automatic review requests.
> codeowners: setup

- module/go.mod
- module/go.sum
- orchestrator/test_runner/src/happy_path_v2.rs
- tests/container-scripts/setup-validators.sh
Just the sdk update and some minor test fixes.
> Update to Cosmos SDK v0.42.1

- .github/workflows/proto.yml
- module/Makefile
- module/buf.yaml
- module/proto/peggy/v1/attestation.proto
- module/proto/peggy/v1/ethereum_signer.proto
- module/proto/peggy/v1/genesis.proto
- module/proto/peggy/v1/msgs.proto
- module/proto/peggy/v1/pool.proto
- module/proto/peggy/v1/query.proto
- module/proto/peggy/v1/types.proto
- Add buf.yaml with rules for linting
- Fix make proto-lint. Avoid needing to download buf. 
- Lint proto files
- Add protobuf linting and break checking to ci
> proto: add buf.yaml, fix linting

- design/overview.md
- design/relaying-semantics.md
This pull request contains some new documentation. There's a lot of docs to write so I'm starting with the things that are top of mind. If there's some specific documentation you would like let me know.
This pr is complete enough on it's own to merge, or could be expanded with more docs.
> Documentation for relayer semantics and expansion of overview.md

- design/overview.md
- design/relaying-semantics.md
- orchestrator/test_runner/src/bootstrapping.rs
- orchestrator/test_runner/src/main.rs
- orchestrator/test_runner/src/utils.rs
Allows the test runner to be configured with environment variables to enable the docker based test environment.
> Override localhost in the test runner with environment variable
